services:
  bot_service:
    profiles: [aws]
    image: bot:server
    build: https://github.com/Pewchenka/BotShop.git
    env_file:
      - ./.env  
    restart: always
    pull_policy: build

  bot_service_local:
    profiles: [local]
    build:
      context: .
      dockerfile: DockerfileLocal
    image: bot:local
    volumes:
      - ./:/app
    env_file:
      - ./.env  
    restart: always

